# Generated by Django 3.1.5 on 2022-04-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0002_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
